/// Flutter icons HessDeck
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HessDeck
///      fonts:
///       - asset: fonts/HessDeck.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HessDeck {
  HessDeck._();

  static const _kFontFam = 'HessDeck';
  static const String? _kFontPkg = null;

  static const IconData applemusic = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData obsstudio = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData streamelements = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
