name: spotify_api
version: 1.0.0
description: A package for Spotify WEB API integration

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  http: ^1.1.0
  url_launcher: ^6.0.12
  uni_links: ^0.5.1
  webview_flutter: ^3.0.0
  # Add any other dependencies if needed